# Generated by Django 3.2.14 on 2023-01-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230121_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientslist',
            old_name='quantity',
            new_name='amount',
        ),
    ]
