# Generated by Django 3.2.14 on 2023-01-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=256, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
